### ISSUE TITLE
Command stderr being piped to wasi log

### ISSUE THREAD

**Issue by guybedford** [bytecodealliance/preview2-prototyping#57]
When running a WASI command under preview2, stderr is currently being piped to wasi log. This results in a couple of problems:

1. Each WASI log call is made individually, so buffered output that would usually appear on the same line is split over multiple lines and collated with potential log level / context info
2. This seems inconsistent with stdout running through wasi-poll write stream

**Comment by sunfishcode** [comment]
I posted #59 with a potential fix for this. It fixes the problem of splitting messages over multiple lines, and the log level / context info problem.

The inconsistency between stdout and stderr is something we're exploring. It's indeed not How Unix Does Things, but it seems to be a more useful default:
 - Stdout represents the deliverable output of the program, which might be directly connected to another program. It's I/O, meanng it's fallible, blocking (and in the future will be able to be async), and
 - Stderr represents diagnostic messages from the program. It's infallible. The program should never have to think about failures on stderr, because where would it describe the error to if stderr itself is failing?
